# Generated by Django 5.2.1 on 2025-05-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codactividad', models.AutoField(db_column='codActividad', primary_key=True, serialize=False)),
                ('nombreactividad', models.CharField(db_column='nombreActividad')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('codantecedente', models.AutoField(db_column='codAntecedente', primary_key=True, serialize=False)),
                ('nombreantecedente', models.CharField(db_column='nombreAntecedente')),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('codcausa', models.AutoField(db_column='codCausa', primary_key=True, serialize=False)),
                ('nombrecausa', models.CharField(db_column='nombreCausa')),
            ],
        ),
        migrations.CreateModel(
            name='Ccaa',
            fields=[
                ('codccaa', models.AutoField(db_column='codCCAA', primary_key=True, serialize=False)),
                ('nombreccaa', models.CharField(db_column='nombreCCAA')),
            ],
        ),
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('coddeteccion', models.AutoField(db_column='codDeteccion', primary_key=True, serialize=False)),
                ('nombredeteccion', models.CharField(db_column='nombreDeteccion')),
            ],
        ),
        migrations.CreateModel(
            name='Extraccion',
            fields=[
                ('codextraccion', models.AutoField(db_column='codExtraccion', primary_key=True, serialize=False)),
                ('nombreextraccion', models.CharField(db_column='nombreExtraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Factorriesgo',
            fields=[
                ('codfactorriesgo', models.AutoField(db_column='codFactorRiesgo', primary_key=True, serialize=False)),
                ('nombrefactorriesgo', models.CharField(db_column='nombreFactorRiesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('codintervencion', models.AutoField(db_column='codIntervencion', primary_key=True, serialize=False)),
                ('nombreintervencion', models.CharField(db_column='nombreIntervencion')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('codlocalizacion', models.AutoField(db_column='codLocalizacion', primary_key=True, serialize=False)),
                ('nombrelocalizacion', models.CharField(db_column='nombreLocalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Materialrescate',
            fields=[
                ('codmaterialrescate', models.AutoField(db_column='codMaterialRescate', primary_key=True, serialize=False)),
                ('nombrematerialrescate', models.CharField(db_column='nombreMaterialRescate')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codnacionalidad', models.AutoField(db_column='codNacionalidad', primary_key=True, serialize=False)),
                ('nombrenacionalidad', models.CharField(db_column='nombreNacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('codorigen', models.AutoField(db_column='codOrigen', primary_key=True, serialize=False)),
                ('nombreorigen', models.CharField(db_column='nombreOrigen')),
            ],
        ),
        migrations.CreateModel(
            name='Primerinterviniente',
            fields=[
                ('codprimerinterviniente', models.AutoField(db_column='codPrimerInterviniente', primary_key=True, serialize=False)),
                ('nombreprimerinterviniente', models.CharField(db_column='nombrePrimerInterviniente')),
            ],
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('codpronostico', models.AutoField(db_column='codPronostico', primary_key=True, serialize=False)),
                ('nombrepronostico', models.CharField(db_column='nombrePronostico')),
            ],
        ),
        migrations.CreateModel(
            name='Reanimacion',
            fields=[
                ('codreanimacion', models.AutoField(db_column='codReanimacion', primary_key=True, serialize=False)),
                ('nombrereanimacion', models.CharField(db_column='nombreReanimacion')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('codriesgo', models.AutoField(db_column='codRiesgo', primary_key=True, serialize=False)),
                ('nombreriesgo', models.CharField(db_column='nombreRiesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipoahogamiento',
            fields=[
                ('codtipoahogamiento', models.AutoField(db_column='codTipoAhogamiento', primary_key=True, serialize=False)),
                ('nombretipoahogamiento', models.CharField(db_column='nombreTipoAhogamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Zonavigilada',
            fields=[
                ('codzonavigilada', models.AutoField(db_column='codZonaVigilada', primary_key=True, serialize=False)),
                ('nombrezonavigilada', models.CharField(db_column='nombreZonaVigilada')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codprovincia', models.AutoField(db_column='codProvincia', primary_key=True, serialize=False)),
                ('nombreprovincia', models.CharField(db_column='nombreProvincia')),
                ('codccaa', models.ForeignKey(db_column='codCCAA', on_delete=django.db.models.deletion.DO_NOTHING, to='home.ccaa')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codlocalidad', models.AutoField(db_column='codLocalidad', primary_key=True, serialize=False)),
                ('nombrelocalidad', models.CharField(db_column='nombreLocalidad')),
                ('provincia', models.ForeignKey(db_column='provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='home.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('codincidente', models.AutoField(db_column='codIncidente', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('titular', models.CharField()),
                ('latitud', models.TextField()),
                ('longitud', models.TextField()),
                ('enlace', models.CharField(blank=True, null=True)),
                ('actividad', models.ForeignKey(db_column='actividad', on_delete=django.db.models.deletion.DO_NOTHING, to='home.actividad')),
                ('deteccion', models.ForeignKey(db_column='deteccion', on_delete=django.db.models.deletion.DO_NOTHING, to='home.deteccion')),
                ('intervencion', models.ForeignKey(db_column='intervencion', on_delete=django.db.models.deletion.DO_NOTHING, to='home.intervencion')),
                ('localidad', models.ForeignKey(db_column='localidad', on_delete=django.db.models.deletion.DO_NOTHING, to='home.localidad')),
                ('localizacion', models.ForeignKey(db_column='localizacion', on_delete=django.db.models.deletion.DO_NOTHING, to='home.localizacion')),
                ('riesgo', models.ForeignKey(db_column='riesgo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.riesgo')),
                ('zona', models.ForeignKey(db_column='zona', on_delete=django.db.models.deletion.DO_NOTHING, to='home.zonavigilada')),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('codvictima', models.AutoField(db_column='codVictima', primary_key=True, serialize=False)),
                ('sexo', models.CharField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('extraccion', models.ForeignKey(db_column='extraccion', on_delete=django.db.models.deletion.DO_NOTHING, to='home.extraccion')),
                ('incidente', models.ForeignKey(db_column='incidente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.incidente')),
                ('materialrescate', models.ForeignKey(db_column='materialRescate', on_delete=django.db.models.deletion.DO_NOTHING, to='home.materialrescate')),
                ('nacionalidad', models.ForeignKey(db_column='nacionalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='home.nacionalidad')),
                ('origen', models.ForeignKey(db_column='origen', on_delete=django.db.models.deletion.DO_NOTHING, to='home.origen')),
                ('primerinterviniente', models.ForeignKey(db_column='primerInterviniente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.primerinterviniente')),
                ('pronostico', models.ForeignKey(db_column='pronostico', on_delete=django.db.models.deletion.DO_NOTHING, to='home.pronostico')),
                ('reanimacion', models.ForeignKey(db_column='reanimacion', on_delete=django.db.models.deletion.DO_NOTHING, to='home.reanimacion')),
                ('tipoahogamiento', models.ForeignKey(db_column='tipoAhogamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='home.tipoahogamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Factorriesgovictima',
            fields=[
                ('pk', models.CompositePrimaryKey('factorriesgo', 'victima', blank=True, editable=False, primary_key=True, serialize=False)),
                ('factorriesgo', models.ForeignKey(db_column='factorRiesgo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.factorriesgo')),
                ('victima', models.ForeignKey(db_column='victima', on_delete=django.db.models.deletion.DO_NOTHING, to='home.victima')),
            ],
        ),
        migrations.CreateModel(
            name='Causavictima',
            fields=[
                ('pk', models.CompositePrimaryKey('causa', 'victima', blank=True, editable=False, primary_key=True, serialize=False)),
                ('causa', models.ForeignKey(db_column='causa', on_delete=django.db.models.deletion.DO_NOTHING, to='home.causa')),
                ('victima', models.ForeignKey(db_column='victima', on_delete=django.db.models.deletion.DO_NOTHING, to='home.victima')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentevictima',
            fields=[
                ('pk', models.CompositePrimaryKey('antecedente', 'victima', blank=True, editable=False, primary_key=True, serialize=False)),
                ('antecedente', models.ForeignKey(db_column='antecedente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.antecedente')),
                ('victima', models.ForeignKey(db_column='victima', on_delete=django.db.models.deletion.DO_NOTHING, to='home.victima')),
            ],
        ),
    ]
