# Generated by Django 5.2.1 on 2025-05-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='antecedente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='antecedentevictima',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='causa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='causavictima',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ccaa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deteccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='extraccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='factorriesgo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='factorriesgovictima',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='intervencion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localizacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialrescate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='origen',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='primerinterviniente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pronostico',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reanimacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='riesgo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoahogamiento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='victima',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='zonavigilada',
            options={'managed': True},
        ),
    ]
