# Generated by Django 5.2.1 on 2025-05-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_actividad_options_alter_antecedente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='antecedente',
            table='Antecedente',
        ),
    ]
