# Generated by Django 5.2.1 on 2025-05-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_antecedente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividad',
            table='Actividad',
        ),
        migrations.AlterModelTable(
            name='antecedentevictima',
            table='AntecedenteVictima',
        ),
        migrations.AlterModelTable(
            name='causa',
            table='Causa',
        ),
        migrations.AlterModelTable(
            name='causavictima',
            table='CausaVictima',
        ),
        migrations.AlterModelTable(
            name='ccaa',
            table='CCAA',
        ),
        migrations.AlterModelTable(
            name='deteccion',
            table='Deteccion',
        ),
        migrations.AlterModelTable(
            name='extraccion',
            table='Extraccion',
        ),
        migrations.AlterModelTable(
            name='factorriesgo',
            table='FactorRiesgo',
        ),
        migrations.AlterModelTable(
            name='factorriesgovictima',
            table='FactorRiesgoVictima',
        ),
        migrations.AlterModelTable(
            name='incidente',
            table='Incidente',
        ),
        migrations.AlterModelTable(
            name='intervencion',
            table='Intervencion',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='Localidad',
        ),
        migrations.AlterModelTable(
            name='localizacion',
            table='Localizacion',
        ),
        migrations.AlterModelTable(
            name='materialrescate',
            table='MaterialRescate',
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidad',
        ),
        migrations.AlterModelTable(
            name='origen',
            table='Origen',
        ),
        migrations.AlterModelTable(
            name='primerinterviniente',
            table='PrimerInterviniente',
        ),
        migrations.AlterModelTable(
            name='pronostico',
            table='Pronostico',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='Provincia',
        ),
        migrations.AlterModelTable(
            name='reanimacion',
            table='Reanimacion',
        ),
        migrations.AlterModelTable(
            name='riesgo',
            table='Riesgo',
        ),
        migrations.AlterModelTable(
            name='tipoahogamiento',
            table='TipoAhogamiento',
        ),
        migrations.AlterModelTable(
            name='victima',
            table='Victima',
        ),
        migrations.AlterModelTable(
            name='zonavigilada',
            table='ZonaVigilada',
        ),
    ]
